# Generated by Django 3.1.5 on 2021-03-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
        migrations.AddField(
            model_name='post',
            name='Desc',
            field=models.TextField(default=datetime.time),
            preserve_default=False,
        ),
    ]
