# Generated by Django 3.1.5 on 2021-03-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210307_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Desc',
            new_name='desc',
        ),
    ]
